export const skeinRegistryAbi = [
  {
    type: "function",
    name: "salt",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "invoiceId",
    inputs: [{ name: "fingerprintRoot", type: "bytes32" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "check",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [
      { name: "pledged", type: "bool" },
      { name: "lender", type: "address" },
      { name: "blockNumber", type: "uint256" },
      { name: "settled", type: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fundAndPledge",
    inputs: [
      { name: "id", type: "bytes32" },
      { name: "seller", type: "address" },
      { name: "evidenceHash", type: "bytes32" },
      { name: "verdictHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "releasePledge",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repay",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "recentIds",
    inputs: [
      { name: "from", type: "uint256" },
      { name: "count", type: "uint256" },
    ],
    outputs: [{ name: "page", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lenderIds",
    inputs: [{ name: "lender", type: "address" }],
    outputs: [{ name: "", type: "bytes32[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPledge",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "lender", type: "address" },
          { name: "seller", type: "address" },
          { name: "advance", type: "uint256" },
          { name: "evidenceHash", type: "bytes32" },
          { name: "verdictHash", type: "bytes32" },
          { name: "pledgedAt", type: "uint64" },
          { name: "blockNumber", type: "uint256" },
          { name: "settled", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pledgeCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ids",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  { type: "error", name: "AlreadyPledged", inputs: [{ name: "invoiceId", type: "bytes32" }, { name: "lender", type: "address" }, { name: "blockNumber", type: "uint256" }] },
  { type: "error", name: "ZeroSeller", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "NotLender", inputs: [] },
  { type: "error", name: "NotSeller", inputs: [] },
  { type: "error", name: "NotOpen", inputs: [] },
  { type: "error", name: "AlreadySettled", inputs: [] },
  { type: "error", name: "WrongRepayment", inputs: [{ name: "expected", type: "uint256" }] },
  { type: "error", name: "TransferFailed", inputs: [] },
  {
    type: "event",
    name: "Pledged",
    inputs: [
      { name: "invoiceId", type: "bytes32", indexed: true },
      { name: "lender", type: "address", indexed: true },
      { name: "seller", type: "address", indexed: true },
      { name: "advance", type: "uint256", indexed: false },
      { name: "evidenceHash", type: "bytes32", indexed: false },
      { name: "verdictHash", type: "bytes32", indexed: false },
      { name: "blockNumber", type: "uint256", indexed: false },
    ],
  },
] as const;
