[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200
evm_version = "osaka"
ffi = false

[fuzz]
runs = 512

[invariant]
runs = 128
depth = 32

[rpc_endpoints]
arc = "https://arc-mainnet.g.alchemy.com/v2/alch_PSz9cPwjUFKJ0jJ2fsiqn"
arcTestnet = "https://rpc.mainnet.arc.io"
